FROM ubuntu:18.04

RUN apt update && \
    apt -y install autoconf bison clang flex libboost-dev libboost-all-dev libc6-dev make wget g++

RUN wget https://osdn.net/dl/rctools/librcsc-4.1.0.tar.gz && \
    tar xvzf librcsc-4.1.0.tar.gz && \
    cd librcsc-4.1.0 && \
    ./configure && \
    make && \
    make install

COPY sample-teams/agent2d-3.1.1 /root/agent2d-3.1.1

RUN apt-get install gcc

RUN cd root/agent2d-3.1.1  && \
    ./configure && \
    make && \
    make install

RUN ldconfig && \
    apt update && \
    apt install -y libboost-filesystem1.65.1 libboost-system1.65.1 iputils-ping

WORKDIR /root/agent2d-3.1.1/src/

CMD bash -c "./start.sh -h rcssserver"
