FROM ubuntu:18.04 AS build
ARG VERSION=5.1.1
WORKDIR /home/developer

RUN apt update && \
    apt -y install autoconf bison clang flex libboost-dev libboost-all-dev libc6-dev make wget libqt4-dev \
    libfontconfig1-dev libaudio-dev libxt-dev libsm-dev libice-dev libxi-dev libxrender-dev

RUN wget https://osdn.net/dl/rctools/librcsc-4.0.0.tar.gz && \
    tar xvzf librcsc-4.0.0.tar.gz && \
    cd librcsc-4.0.0 && \
    ./configure && \
    make && \
    make install

RUN wget https://osdn.net/dl/rctools/soccerwindow2-${VERSION}.tar.gz && \
    tar xfz soccerwindow2-${VERSION}.tar.gz && \
    cd soccerwindow2-${VERSION} && \
    ./configure && \
    make && \
    make install

FROM ubuntu:18.04
WORKDIR /home/developer

# Copy lib files
COPY --from=build /usr/local/lib /usr/local/lib
COPY --from=build /usr/lib /usr/lib
COPY --from=build /lib /lib

# Copy font files
COPY --from=build /etc/fonts /etc/fonts
COPY --from=build /usr/include/X11/fonts /usr/include/X11/fonts
COPY --from=build /usr/share/fonts /usr/share/fonts
COPY --from=build /usr/local/share/fonts /usr/local/share/fonts

# Copy bin files
COPY --from=build /usr/local/bin /usr/local/bin
RUN mkdir -p /home/developer
COPY --from=build /usr/local/bin/soccerwindow2 /home/developer

##########################
# This was basically copied from http://fabiorehm.com/blog/2014/09/11/running-gui-apps-with-docker/
RUN export uid=1000 gid=1000 && \
    mkdir -p /home/developer && \
    mkdir -p /etc/sudoers.d && \
    echo "developer:x:${uid}:${gid}:Developer,,,:/home/developer:/bin/bash" >> /etc/passwd && \
    echo "developer:x:${uid}:" >> /etc/group && \
    echo "developer ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/developer && \
    chmod 0440 /etc/sudoers.d/developer && \
    chown ${uid}:${gid} -R /home/developer

USER developer
ENV HOME /home/developer
##########################

CMD bash -c 'soccerwindow2 --host rcssserver || sleep infinity'
